### ISSUE TITLE
Deathcounter still on screen after revive. Kills player when finished.

### ISSUE THREAD

**Issue by alexandre-leites** [happydayz-enigma/Enigma_Exile_Revive#3]
I've updated everything to the lastest version and also merged your changes to the recent exile version. However I still have the deathcounter after reviving a player. And when it gets to ZERO, the player dies.

**Comment by arjona00** [comment]
The same on my server. 
Thankiu for all, great mod.

**Comment by hpy** [comment]
should be fixed in latest version

**Comment by alexandre-leites** [comment]
Confirming as fixed.

**Comment by arjona00** [comment]
Fixed verified on my server
