### ISSUE TITLE
Player character delete on 1.0.1

### ISSUE THREAD

**Issue by swiftplague** [happydayz-enigma/Enigma_Exile_Revive#4]
Since 1.0.1 when a character revives on my server the script does not revive them and their character is deleted and they can not get their body.

Is there a fix or did i miss something.

**Comment by ReDBaroN1** [comment]
I'm guessing this is due to the fact that exile have touched these files in the 101 update to revert the group system back to how it was before 098/100.

We'll need to wait until happydayz updates those files for enigma revive.

**Comment by hpy** [comment]
should be fixed now
